### ISSUE TITLE
[FEATURE] Alternative datastorage options

### ISSUE THREAD

**Issue by nicotravassos** [twilio/twilio-chat-console-webapp.js#10]
Dear @aleksandrsivanovs,

Kindly add alternative data options to this example such as `PostgreSQL` I would really appreciate it.

User can define which database he would like to use:

```
"firebaseConfig": {
      "enabled": "true/false",
      "apiKey": "",
      "authDomain": "",
      "databaseURL": "",
      "projectId": "",
      "storageBucket": "",
      "messagingSenderId": ""
    }
```
OR like this:
```
"chatClient": {
    "databaseProvider": "PostgreSQL",
}
```

**Comment by nicotravassos** [comment]
Actually do not think this possible because you are using FCM.

**Comment by aleksandrsivanovs** [comment]
Hi!

yeah, we need FCM

**Comment by nicotravassos** [comment]
Thanks @aleksandrsivanovs for your response.
