### ISSUE TITLE
Need MIME type

### ISSUE THREAD

**Issue by spalmertwilio** [twilio/twilio-chat-console-webapp.js#6]
In app.js https://github.com/twilio/twilio-chat-console-webapp.js/blob/master/app.js

need to add in  line:
`res.type('text/javascript');`

Into block:

```
app.get('/firebase-config.js', function(req, res) {
  if (config.fcmConfig && config.fcmConfig.firebaseConfig) {
  res.type('text/javascript');
    res.send('const firebaseConfig = ' + JSON.stringify(config.fcmConfig.firebaseConfig));
  } else {
    res.send('const firebaseConfig;');
  }
});

```
To get rid of mime type errors.

**Comment by aleksandrsivanovs** [comment]
please review https://github.com/twilio/twilio-chat-console-webapp.js/commit/57fa9e34374388d288edef80c6269ec106f9ce13
